// Textos en español. 'r' = norma / requisito a confirmar con la autoridad; 't' = consejo práctico.
export default {
  dir: 'ltr', locale: 'es-ES',
  docTitle: 'Lista de verificación del regreso de verano a Marruecos',
  subtitle: 'De la salida a la llegada y la vuelta: documentos, transporte, coche, dinero, salud, alojamiento y trámites.',
  edition: 'Edición de octubre de 2026',
  verify: 'Las normas cambian: compruébalas antes de viajar.',
  legendTitle: 'Cómo leer esta lista',
  legendRule: 'Norma',
  legendRuleText: 'requisito o norma publicados en nuestras guías. Confírmalo con la administración, el consulado, la aseguradora o la compañía correspondiente.',
  legendTip: 'Consejo',
  legendTipText: 'buena práctica, no obligatoria.',
  legendBox: 'Marca la casilla cuando esté hecho.',
  keyDatesTitle: 'Mis fechas clave',
  keyDates: ['Fecha de salida', 'Fecha de regreso', 'Ferri / vuelo (n.º de reserva)', 'Seguro del coche válido hasta', 'Pasaportes válidos hasta', 'Entrada del vehículo en Marruecos el'],
  sections: [
    { title: 'Antes de salir', items: [
      ['t', 'Reserva el ferri **en abril-mayo** si sales en julio-agosto: las mejores tarifas se agotan pronto.'],
      ['t', 'Anota las fechas de caducidad de los pasaportes y documentos de identidad de **toda la familia**.'],
      ['t', 'Calcula tu presupuesto (travesía, combustible, peajes, paradas, gastos en destino) con la calculadora del sitio.'],
      ['t', 'Si viajas con el coche, planifica una revisión mecánica antes de salir (véase «Vehículo»).'],
      ['t', 'Avisa a tu banco de que viajas al extranjero y prueba tu tarjeta.'],
    ]},
    { title: 'Documentos de los adultos', items: [
      ['r', '**Pasaporte válido** durante toda la estancia, para cada miembro de la familia. Los marroquíes también pueden presentar una CNIE válida, pero lleva un pasaporte por si hay un control o un vuelo de regreso.'],
      ['r', 'Visitantes extranjeros: comprueba con las autoridades el visado y las condiciones de entrada según tu nacionalidad (véase la guía de visado del sitio).'],
      ['t', '¿Debes renovar el pasaporte o la CNIE? **Anticípate de 3 a 4 meses**: las citas consulares se llenan rápido en verano.'],
      ['r', 'La inscripción consular debe estar al día antes de pedir una renovación en el consulado.'],
      ['t', 'Guarda una copia digital y otra en papel de tus documentos, separadas de los originales.'],
    ]},
    { title: 'Documentos de los niños y de las mascotas', items: [
      ['r', '**Pasaporte individual válido** para cada niño, sea cual sea su edad.'],
      ['t', 'Lleva el libro de familia (o un extracto de la partida de nacimiento) para acreditar el vínculo con los padres.'],
      ['r', 'Menor residente en Francia que viaja **sin uno de sus padres**: autorización de salida del territorio (formulario Cerfa n.º 15646, firmado por un progenitor, con copia de su documento de identidad).'],
      ['t', 'Si el niño no viaja con ambos padres, lleva también una autorización parental firmada, a ser posible legalizada: los agentes marroquíes pueden pedirla.'],
      ['r', 'Perro o gato: microchip, vacuna antirrábica anotada en el pasaporte europeo, certificado sanitario con el modelo de la ONSSA visado poco antes de la salida (confirma el plazo exacto con tu veterinario).'],
      ['t', 'Para volver a la UE con una mascota, la prueba de anticuerpos antirrábicos tarda varias semanas. Empieza **al menos 4 meses** antes del regreso.'],
    ]},
    { title: 'Transporte: ferri, avión o carretera', items: [
      ['t', 'Ferri: en agosto suelen exigirse billetes con fecha fija. Evita los fines de semana y el principio o final de mes.'],
      ['t', 'Llega al puerto **unas 3 horas antes** del embarque en temporada alta.'],
      ['t', 'Guarda billetes y reservas sin conexión **y** imprímelos.'],
      ['t', 'Comprueba si los horarios del billete están en hora local: la diferencia horaria con Marruecos puede variar según la época.'],
      ['t', 'Avión: revisa el equipaje permitido de tu compañía antes de comprar regalos voluminosos.'],
      ['t', 'Carretera: haz una pausa cada 2 horas, sobre todo de noche en España. Ten agua, algo de comer y los documentos a mano.'],
      ['t', 'Sin coche en destino: reserva con antelación los trayectos en autobús o tren (CTM, ONCF).'],
    ]},
    { title: 'Vehículo (si viajas en coche)', items: [
      ['r', 'Permiso de circulación **original** (o autorización / poder del propietario si no está a tu nombre) y carné de conducir válido.'],
      ['r', '**Seguro válido en Marruecos**: en la carta verde, el código **MA** debe figurar y no estar tachado. Si no, contrata el seguro de frontera al llegar (se vende por tramos de duración).'],
      ['t', 'Pide a tu aseguradora, **antes de salir**, una carta verde válida en Marruecos. No hay un precio único del seguro de frontera: consulta el precio con quien lo emite.'],
      ['r', 'Admisión temporal: uso estrictamente personal y turístico, declarada en la aduana a la llegada. Conserva el justificante hasta salir de Marruecos.'],
      ['r', 'No dejes conducir tu coche a un residente en Marruecos sin informarte antes: a menudo está prohibido.'],
      ['t', 'Revisión mecánica: neumáticos (rueda de repuesto incluida), frenos, niveles, aire acondicionado, batería. Carga con orden, nada en la bandeja trasera.'],
      ['t', 'Comprueba la presión de los neumáticos en frío y llena el depósito el día anterior.'],
    ]},
    { title: 'Dinero y aduana', items: [
      ['r', 'Divisas: se exige declaración a la llegada a partir del equivalente de **100 000 DH**.'],
      ['t', 'Lleva algo de efectivo para la carretera y los peajes; los dírhams se obtienen en Marruecos (cajeros).'],
      ['t', 'Planifica con antelación las transferencias de dinero y compara su coste real antes de enviarlas.'],
      ['r', 'Regalos: los efectos personales y los regalos razonables suelen pasar; las grandes cantidades o varios artículos nuevos idénticos (pantallas, móviles, electrodomésticos) pueden tributar. En caso de duda, declara.'],
      ['r', 'Dron: su importación está prohibida sin autorización administrativa previa. Déjalo en casa.'],
      ['t', 'Conserva las facturas de las compras importantes.'],
    ]},
    { title: 'Salud', items: [
      ['t', 'Revisa tus vacunas habituales. Para quien viaja desde Europa, nuestras guías no indican ninguna vacuna obligatoria; consulta a tu médico.'],
      ['t', 'Contrata un seguro de viaje con límite médico alto y repatriación: la tarjeta sanitaria europea no se aplica en Marruecos.'],
      ['r', 'Medicamentos de uso personal: envase original y receta o certificado médico en el equipaje de mano. Sustancias controladas: carta del médico e información previa.'],
      ['t', 'Anota los números de emergencia: SAMU 141, protección civil 15.'],
      ['t', 'Calor del verano: hidrátate, evita el sol del mediodía y bebe agua embotellada.'],
    ]},
    { title: 'Alojamiento y paradas', items: [
      ['t', 'Reserva las etapas si el trayecto es largo (una noche en España, una en Tánger) y revisa las condiciones de cancelación.'],
      ['t', 'Apunta en papel la dirección de tu primer alojamiento y un teléfono de contacto en Marruecos.'],
      ['t', 'Con mascota: confirma que cada alojamiento y cada camarote la admiten.'],
      ['t', 'Avisa a la familia de tu hora de llegada, en hora local.'],
    ]},
    { title: 'Trámites que conviene adelantar', items: [
      ['t', 'Consigue una SIM o eSIM para la llegada y descarga mapas sin conexión.'],
      ['t', 'Trámites consulares (pasaporte, CNIE): pide cita varios meses antes de salir.'],
      ['t', 'Operación Marhaba: las áreas de acogida (puertos, aeropuertos, carretera) ofrecen información y asistencia en verano. Las fechas las publica cada año la Fundación Mohammed V para la Solidaridad.'],
    ]},
    { title: 'A la llegada: comprobaciones', items: [
      ['r', 'Coche: declaración de admisión temporal hecha y justificante guardado en el coche.'],
      ['r', 'Certificado del seguro (carta verde con MA o seguro de frontera) guardado en el coche.'],
      ['t', 'Revisa las fechas y los datos de los documentos que te entreguen antes de salir del puesto.'],
      ['t', 'Saca algunos dírhams y activa tu SIM / eSIM.'],
      ['t', 'Avisa a la familia de que has llegado.'],
    ]},
    { title: 'La vuelta: vehículo y 180 días', items: [
      ['r', 'Admisión temporal: **180 días por año natural**, en una o varias estancias. No se puede prorrogar, salvo disposiciones especiales de fin de año que debes consultar en la aduana. Superar el plazo conlleva sanciones.'],
      ['t', 'Anota las fechas de entrada y salida de cada viaje (véase «Mis fechas clave») o usa el contador del sitio.'],
      ['r', 'Conserva el justificante de admisión y el seguro vigentes hasta salir de Marruecos.'],
      ['r', 'Mascota: certificado sanitario de salida con el modelo de la ONSSA, con un plazo de validez corto. Confírmalo con tu veterinario.'],
      ['t', 'Los regresos se concentran a finales de agosto: si puedes, desplaza la salida unos días y llega temprano al puerto.'],
      ['t', 'Comprueba que el seguro y los pasaportes cubren también el viaje de vuelta.'],
    ]},
  ],
  guidesTitle: 'Para ir más allá: guías del sitio',
  guides: [
    ['summer-checklist', 'Lista del regreso de verano (versión interactiva)'],
    ['marhaba-guide', 'Operación Marhaba'],
    ['ferry-guide', 'Ferri a Marruecos'],
    ['car-180-days', 'Coche en Marruecos y regla de los 180 días'],
    ['car-insurance', 'Seguro del coche: carta verde o seguro de frontera'],
    ['customs', 'Aduana: qué puedes llevar'],
    ['passport-cnie', 'Pasaporte y CNIE desde el extranjero'],
    ['kids-pets', 'Niños y mascotas'],
    ['health-travellers', 'Salud del viajero'],
  ],
  officialTitle: 'Fuentes oficiales para consultar',
  official: ['Aduana marroquí (ADII): douane.gov.ma', 'Fundación Mohammed V para la Solidaridad (Marhaba): fm5.ma', 'Citas consulares: rdv.consulat.ma', 'Autorización de salida de menores (Francia): service-public.fr', 'Seguro de frontera: web del organismo que lo emite (por ejemplo CAT)'],
  disclaimerTitle: 'Información general, no asesoramiento jurídico ni fiscal',
  disclaimer: 'Esta lista recoge información publicada en nuestras guías en la fecha de edición (octubre de 2026). Las normas, importes y plazos cambian y dependen de tu situación. Compruébalos antes de viajar con la aduana (ADII), tu consulado, tu aseguradora y tu compañía de transporte. Este documento no sustituye sus indicaciones. No contiene enlaces de afiliación. Traducción automática pendiente de revisión humana.',
  notes: 'Notas',
  page: 'Página',
};
