// Textes FR de la check-list. 'r' = règle / exigence à confirmer auprès de l'autorité ; 't' = conseil pratique.
export default {
  dir: 'ltr', locale: 'fr-FR',
  docTitle: 'Check-list du retour d’été au Maroc',
  subtitle: 'Du départ à l’arrivée, puis au retour : documents, transport, voiture, argent, santé, logement et démarches.',
  edition: 'Édition octobre 2026',
  verify: 'Les règles changent : vérifiez avant de partir.',
  legendTitle: 'Comment lire cette liste',
  legendRule: 'Règle',
  legendRuleText: 'exigence ou règle publiée dans nos guides. À confirmer auprès de l’administration, du consulat, de l’assureur ou de la compagnie concernés.',
  legendTip: 'Conseil',
  legendTipText: 'bonne pratique, non obligatoire.',
  legendBox: 'Cochez une case quand c’est fait.',
  keyDatesTitle: 'Mes dates clés',
  keyDates: ['Départ le', 'Retour le', 'Ferry / vol (n° de réservation)', 'Assurance auto valable jusqu’au', 'Passeports valides jusqu’au', 'Entrée du véhicule au Maroc le'],
  sections: [
    { title: 'Avant le départ', items: [
      ['t', 'Réservez le ferry **dès avril-mai** pour un départ en juillet-août : les meilleurs tarifs partent tôt.'],
      ['t', 'Notez les dates de validité des passeports et cartes d’identité de **toute la famille**.'],
      ['t', 'Estimez votre budget (traversée, carburant, péages, haltes, dépenses sur place) avec le calculateur du site.'],
      ['t', 'Si vous venez avec la voiture, prévoyez un bilan mécanique avant le départ (voir « Véhicule »).'],
      ['t', 'Prévenez votre banque que vous voyagez à l’étranger et testez votre carte bancaire.'],
    ]},
    { title: 'Documents des adultes', items: [
      ['r', '**Passeport valide** pour tout le séjour, pour chaque membre de la famille. Les Marocains peuvent aussi présenter une CNIE valide, mais gardez un passeport en cas de contrôle ou de vol retour.'],
      ['r', 'Visiteurs étrangers : vérifiez le visa et les conditions d’entrée selon votre nationalité auprès des autorités (voir le guide visa du site).'],
      ['t', 'Passeport ou CNIE à renouveler ? **Anticipez de 3 à 4 mois** : les rendez-vous consulaires se remplissent vite en été.'],
      ['r', 'Immatriculation consulaire à jour avant toute demande de renouvellement au consulat.'],
      ['t', 'Gardez une copie numérique et une copie papier de vos documents, séparées des originaux.'],
    ]},
    { title: 'Documents des enfants et des animaux', items: [
      ['r', '**Passeport individuel valide** pour chaque enfant, quel que soit son âge.'],
      ['t', 'Emportez le livret de famille (ou un extrait d’acte de naissance) pour prouver le lien avec les parents.'],
      ['r', 'Mineur résidant en France qui voyage **sans l’un de ses parents** : autorisation de sortie du territoire (formulaire Cerfa n° 15646, signé par un parent, avec copie de sa pièce d’identité).'],
      ['t', 'Si l’enfant ne voyage pas avec ses deux parents, prévoyez aussi une autorisation parentale signée, idéalement légalisée : les agents marocains peuvent la demander.'],
      ['r', 'Chien ou chat : puce, vaccin antirabique consigné dans le passeport européen, certificat sanitaire au modèle ONSSA visé peu avant le départ (confirmez le délai avec votre vétérinaire).'],
      ['t', 'Retour en UE avec un animal : le titrage antirabique demande plusieurs semaines. Commencez **au moins 4 mois** avant le retour.'],
    ]},
    { title: 'Transport : ferry, avion ou route', items: [
      ['t', 'Ferry : en août, les billets à date fixe sont généralement exigés. Évitez les week-ends et les débuts/fins de mois.'],
      ['t', 'Arrivez au port **environ 3 heures avant** l’embarquement en haute saison.'],
      ['t', 'Enregistrez billets et réservations hors ligne **et** imprimez-les.'],
      ['t', 'Vérifiez si l’horaire de votre billet est en heure locale : le décalage horaire avec le Maroc peut varier selon la saison.'],
      ['t', 'Avion : vérifiez la franchise de bagages de votre compagnie avant d’acheter des cadeaux volumineux.'],
      ['t', 'Route : pause toutes les 2 heures, surtout de nuit en Espagne. Gardez eau, en-cas et papiers à portée de main.'],
      ['t', 'Sans voiture sur place : réservez à l’avance vos trajets en bus ou en train (CTM, ONCF).'],
    ]},
    { title: 'Véhicule (si vous venez en voiture)', items: [
      ['r', 'Carte grise **originale** (ou autorisation / procuration du propriétaire si elle n’est pas à votre nom) et permis de conduire valide.'],
      ['r', '**Assurance valable au Maroc** : sur la carte verte, le code **MA** doit être présent et non barré. Sinon, souscrivez l’assurance frontière à l’arrivée (durées par paliers).'],
      ['t', 'Demandez à votre assureur, **avant le départ**, une carte verte valable au Maroc. Il n’existe pas de tarif unique de l’assurance frontière : demandez le prix à l’organisme qui la délivre.'],
      ['r', 'Admission temporaire : usage strictement personnel et touristique, déclaration à la douane à l’arrivée. Gardez le justificatif jusqu’à la sortie du Maroc.'],
      ['r', 'Ne laissez pas un résident au Maroc conduire votre voiture sans vous être renseigné : c’est souvent interdit.'],
      ['t', 'Bilan mécanique : pneus (roue de secours comprise), freins, niveaux, climatisation, batterie. Chargez proprement, rien sur la plage arrière.'],
      ['t', 'Contrôlez la pression des pneus à froid et faites le plein la veille.'],
    ]},
    { title: 'Argent et douane', items: [
      ['r', 'Devises : une déclaration est exigée à l’arrivée à partir de l’équivalent de **100 000 DH**.'],
      ['t', 'Prévoyez un peu de liquide pour la route et les péages ; les dirhams s’obtiennent sur place (distributeurs).'],
      ['t', 'Anticipez vos transferts d’argent et comparez leur coût réel avant de les lancer.'],
      ['r', 'Cadeaux : effets personnels et cadeaux raisonnables passent normalement ; de grandes quantités ou plusieurs articles identiques neufs (écrans, téléphones, électroménager) peuvent être taxés. Dans le doute, déclarez.'],
      ['r', 'Drone : importation interdite sans autorisation administrative préalable. Laissez-le chez vous.'],
      ['t', 'Gardez les factures de vos achats importants.'],
    ]},
    { title: 'Santé', items: [
      ['t', 'Vérifiez vos vaccins de routine. Pour un voyageur venant d’Europe, nos guides n’indiquent aucun vaccin obligatoire ; demandez conseil à votre médecin.'],
      ['t', 'Souscrivez une assurance voyage avec plafond médical élevé et rapatriement : la carte européenne d’assurance maladie ne s’applique pas au Maroc.'],
      ['r', 'Médicaments à usage personnel : emballage d’origine, ordonnance ou certificat médical dans le bagage cabine. Substances contrôlées : lettre du médecin et renseignements préalables.'],
      ['t', 'Notez les urgences : SAMU 141, protection civile 15.'],
      ['t', 'Chaleur d’été : hydratation, pas de soleil de midi, eau en bouteille.'],
    ]},
    { title: 'Logement et haltes', items: [
      ['t', 'Réservez vos étapes si le trajet est long (halte en Espagne, nuit à Tanger) et vérifiez les conditions d’annulation.'],
      ['t', 'Notez sur papier l’adresse de votre premier hébergement et un numéro joignable sur place.'],
      ['t', 'Avec un animal : confirmez que chaque hébergement et chaque cabine l’accepte.'],
      ['t', 'Prévenez la famille de votre heure d’arrivée, en heure locale.'],
    ]},
    { title: 'Démarches à anticiper', items: [
      ['t', 'Procurez-vous une SIM ou une eSIM pour l’arrivée et téléchargez des cartes hors ligne.'],
      ['t', 'Démarches consulaires (passeport, CNIE) : rendez-vous à prendre plusieurs mois avant le départ.'],
      ['t', 'Opération Marhaba : des aires d’accueil (ports, aéroports, route) offrent information et assistance en été. Les dates sont publiées chaque année par la Fondation Mohammed V pour la Solidarité.'],
    ]},
    { title: 'À l’arrivée : vérifications', items: [
      ['r', 'Voiture : déclaration d’admission temporaire faite, justificatif rangé dans la voiture.'],
      ['r', 'Attestation d’assurance (carte verte MA ou assurance frontière) gardée dans la voiture.'],
      ['t', 'Contrôlez les dates et informations des documents remis avant de quitter le poste.'],
      ['t', 'Retirez des dirhams et activez votre SIM / eSIM.'],
      ['t', 'Confirmez votre arrivée à la famille.'],
    ]},
    { title: 'Le retour : véhicule et 180 jours', items: [
      ['r', 'Admission temporaire : **180 jours par année civile**, en une ou plusieurs fois. Ce délai ne se prolonge pas, sauf dispositions particulières de fin d’année à vérifier auprès de la douane. Un dépassement entraîne des sanctions.'],
      ['t', 'Notez vos dates d’entrée et de sortie à chaque voyage (voir « Mes dates clés ») ou utilisez le compteur du site.'],
      ['r', 'Gardez le justificatif d’admission et l’assurance valides jusqu’à la sortie du Maroc.'],
      ['r', 'Animal : certificat sanitaire de sortie au modèle ONSSA, avec une fenêtre de validité courte. Confirmez-la avec le vétérinaire.'],
      ['t', 'Les retours se concentrent fin août : si possible, décalez de quelques jours et arrivez tôt au port.'],
      ['t', 'Vérifiez que l’assurance et les passeports couvrent bien le retour.'],
    ]},
  ],
  guidesTitle: 'Pour aller plus loin : les guides du site',
  guides: [
    ['summer-checklist', 'Check-list du retour d’été (version interactive)'],
    ['marhaba-guide', 'Opération Marhaba'],
    ['ferry-guide', 'Ferry pour le Maroc'],
    ['car-180-days', 'Voiture MRE et règle des 180 jours'],
    ['car-insurance', 'Assurance auto : carte verte ou assurance frontière'],
    ['customs', 'Douane : ce que vous pouvez apporter'],
    ['passport-cnie', 'Passeport et CNIE depuis l’étranger'],
    ['kids-pets', 'Enfants et animaux'],
    ['health-travellers', 'Santé des voyageurs'],
  ],
  officialTitle: 'Sources officielles à consulter',
  official: ['Douane marocaine (ADII) : douane.gov.ma', 'Fondation Mohammed V pour la Solidarité (Marhaba) : fm5.ma', 'Rendez-vous consulaires : rdv.consulat.ma', 'Autorisation de sortie du territoire : service-public.fr', 'Assurance frontière : site de l’organisme qui la délivre (par exemple CAT)'],
  disclaimerTitle: 'Information générale, pas un conseil juridique ni fiscal',
  disclaimer: 'Cette liste reprend des informations publiées dans nos guides à la date d’édition (octobre 2026). Les règles, montants et délais évoluent et dépendent de votre situation. Vérifiez avant de partir auprès de la douane (ADII), de votre consulat, de votre assureur et de votre compagnie de transport. Ce document ne remplace pas leurs indications. Cette liste ne contient aucun lien d’affiliation.',
  notes: 'Notes',
  page: 'Page',
};
