// Deutsche Texte. 'r' = Regel / Anforderung, bei der Behörde zu bestätigen; 't' = praktischer Tipp.
export default {
  dir: 'ltr', locale: 'de-DE',
  docTitle: 'Checkliste Sommerreise nach Marokko',
  subtitle: 'Von der Abreise über die Ankunft bis zur Rückkehr: Dokumente, Transport, Auto, Geld, Gesundheit, Unterkunft und Formalitäten.',
  edition: 'Ausgabe Oktober 2026',
  verify: 'Regeln ändern sich: vor der Abreise prüfen.',
  legendTitle: 'So lesen Sie diese Liste',
  legendRule: 'Regel',
  legendRuleText: 'in unseren Ratgebern veröffentlichte Vorgabe. Bitte bei der zuständigen Behörde, dem Konsulat, der Versicherung oder dem Beförderer bestätigen.',
  legendTip: 'Tipp',
  legendTipText: 'bewährte Praxis, nicht verpflichtend.',
  legendBox: 'Kästchen ankreuzen, wenn erledigt.',
  keyDatesTitle: 'Meine wichtigen Daten',
  keyDates: ['Abreise am', 'Rückreise am', 'Fähre / Flug (Buchungsnummer)', 'Kfz-Versicherung gültig bis', 'Reisepässe gültig bis', 'Einreise des Fahrzeugs nach Marokko am'],
  sections: [
    { title: 'Vor der Abreise', items: [
      ['t', 'Buchen Sie die Fähre **im April/Mai** für eine Abreise im Juli/August: die günstigsten Tarife sind früh weg.'],
      ['t', 'Notieren Sie die Ablaufdaten von Reisepässen und Ausweisen **der ganzen Familie**.'],
      ['t', 'Schätzen Sie Ihr Budget (Überfahrt, Kraftstoff, Maut, Zwischenstopps, Ausgaben vor Ort) mit dem Rechner auf der Website.'],
      ['t', 'Reisen Sie mit dem Auto, planen Sie vor der Abreise einen technischen Check (siehe „Fahrzeug“).'],
      ['t', 'Informieren Sie Ihre Bank über die Auslandsreise und testen Sie Ihre Karte.'],
    ]},
    { title: 'Dokumente der Erwachsenen', items: [
      ['r', '**Gültiger Reisepass** für den gesamten Aufenthalt, für jedes Familienmitglied. Marokkanische Staatsangehörige können auch eine gültige CNIE vorlegen; behalten Sie dennoch einen Pass für Kontrollen oder den Rückflug dabei.'],
      ['r', 'Ausländische Besucher: Visum und Einreisebedingungen für Ihre Staatsangehörigkeit bei den Behörden prüfen (siehe Visum-Ratgeber der Website).'],
      ['t', 'Pass oder CNIE erneuern? **Planen Sie 3 bis 4 Monate ein**: Konsulartermine sind im Sommer schnell vergeben.'],
      ['r', 'Die konsularische Registrierung muss vor einem Erneuerungsantrag im Konsulat aktuell sein.'],
      ['t', 'Bewahren Sie eine digitale und eine Papierkopie Ihrer Dokumente getrennt von den Originalen auf.'],
    ]},
    { title: 'Dokumente für Kinder und Haustiere', items: [
      ['r', '**Eigener gültiger Reisepass** für jedes Kind, unabhängig vom Alter.'],
      ['t', 'Nehmen Sie das Familienstammbuch (oder einen Geburtsurkundenauszug) mit, um die Verwandtschaft zu belegen.'],
      ['r', 'Minderjährige mit Wohnsitz in Frankreich, die **ohne einen Elternteil** reisen: Ausreiseerlaubnis (Formular Cerfa Nr. 15646, von einem Elternteil unterschrieben, mit Kopie von dessen Ausweis).'],
      ['t', 'Reist das Kind nicht mit beiden Eltern, führen Sie zusätzlich eine unterschriebene, möglichst beglaubigte Einverständniserklärung mit: Marokkanische Beamte können sie verlangen.'],
      ['r', 'Hund oder Katze: Mikrochip, Tollwutimpfung im EU-Heimtierausweis, Gesundheitszeugnis nach ONSSA-Muster, kurz vor der Abreise amtlich bestätigt (genaue Frist mit dem Tierarzt klären).'],
      ['t', 'Rückreise in die EU mit Tier: Der Tollwut-Antikörpertest dauert mehrere Wochen. Beginnen Sie **mindestens 4 Monate** vor der Rückkehr.'],
    ]},
    { title: 'Transport: Fähre, Flugzeug oder Straße', items: [
      ['t', 'Fähre: Im August sind in der Regel Tickets mit festem Datum erforderlich. Meiden Sie Wochenenden sowie Monatsanfang und -ende.'],
      ['t', 'Seien Sie in der Hauptsaison **etwa 3 Stunden vor** dem Einschiffen im Hafen.'],
      ['t', 'Speichern Sie Tickets und Buchungen offline **und** drucken Sie sie aus.'],
      ['t', 'Prüfen Sie, ob die Zeiten auf dem Ticket Ortszeit sind: Die Zeitdifferenz zu Marokko kann je nach Jahreszeit wechseln.'],
      ['t', 'Flug: Prüfen Sie die Gepäckregeln Ihrer Airline, bevor Sie sperrige Geschenke kaufen.'],
      ['t', 'Straße: Alle 2 Stunden pausieren, besonders nachts in Spanien. Wasser, Snacks und Papiere griffbereit halten.'],
      ['t', 'Ohne Auto vor Ort: Bus- oder Bahnfahrten (CTM, ONCF) rechtzeitig buchen.'],
    ]},
    { title: 'Fahrzeug (bei Anreise mit dem Auto)', items: [
      ['r', '**Original-Fahrzeugschein** (oder Vollmacht des Halters, falls nicht auf Ihren Namen) und gültiger Führerschein.'],
      ['r', '**In Marokko gültiger Versicherungsschutz**: Auf der Grünen Karte muss der Code **MA** vorhanden und nicht durchgestrichen sein. Andernfalls schließen Sie bei der Ankunft die Grenzversicherung ab (Laufzeiten in festen Stufen).'],
      ['t', 'Bitten Sie Ihre Versicherung **vor der Abreise** um eine in Marokko gültige Grüne Karte. Einen einheitlichen Preis der Grenzversicherung gibt es nicht: Fragen Sie den Anbieter nach dem Preis.'],
      ['r', 'Vorübergehende Einfuhr: ausschließlich privat und touristisch, bei der Ankunft beim Zoll anzumelden. Bewahren Sie den Nachweis bis zur Ausreise auf.'],
      ['r', 'Überlassen Sie Ihr Auto keinem Einwohner Marokkos, ohne sich vorher zu informieren: Das ist oft verboten.'],
      ['t', 'Technischer Check: Reifen (Reserverad inklusive), Bremsen, Flüssigkeiten, Klimaanlage, Batterie. Ordentlich beladen, nichts auf der Hutablage.'],
      ['t', 'Reifendruck im kalten Zustand prüfen und am Vortag volltanken.'],
    ]},
    { title: 'Geld und Zoll', items: [
      ['r', 'Devisen: Ab dem Gegenwert von **100.000 MAD** ist bei der Ankunft eine Anmeldung erforderlich.'],
      ['t', 'Nehmen Sie etwas Bargeld für Fahrt und Maut mit; Dirham erhalten Sie in Marokko (Geldautomaten).'],
      ['t', 'Planen Sie Geldtransfers im Voraus und vergleichen Sie die tatsächlichen Kosten.'],
      ['r', 'Geschenke: Persönliche Gegenstände und angemessene Geschenke werden normalerweise durchgelassen; große Mengen oder mehrere identische neue Artikel (Bildschirme, Handys, Haushaltsgeräte) können besteuert werden. Im Zweifel anmelden.'],
      ['r', 'Drohne: Die Einfuhr ist ohne vorherige behördliche Genehmigung verboten. Lassen Sie sie zu Hause.'],
      ['t', 'Heben Sie Rechnungen größerer Anschaffungen auf.'],
    ]},
    { title: 'Gesundheit', items: [
      ['t', 'Prüfen Sie Ihre Standardimpfungen. Für Reisende aus Europa nennen unsere Ratgeber keine Pflichtimpfung; lassen Sie sich ärztlich beraten.'],
      ['t', 'Schließen Sie eine Reiseversicherung mit hoher medizinischer Deckung und Rücktransport ab: Die Europäische Krankenversicherungskarte gilt in Marokko nicht.'],
      ['r', 'Persönliche Medikamente: Originalverpackung, Rezept oder ärztliches Attest im Handgepäck. Kontrollierte Substanzen: Arztbrief und vorherige Auskunft einholen.'],
      ['t', 'Notrufnummern notieren: SAMU 141, Zivilschutz 15.'],
      ['t', 'Sommerhitze: ausreichend trinken, Mittagssonne meiden, Wasser aus Flaschen.'],
    ]},
    { title: 'Unterkunft und Zwischenstopps', items: [
      ['t', 'Buchen Sie Zwischenstopps bei langer Anreise (eine Nacht in Spanien, eine in Tanger) und prüfen Sie die Stornobedingungen.'],
      ['t', 'Notieren Sie die Adresse der ersten Unterkunft und eine Kontaktnummer in Marokko auf Papier.'],
      ['t', 'Mit Haustier: Klären Sie, ob jede Unterkunft und jede Kabine Tiere erlaubt.'],
      ['t', 'Teilen Sie der Familie Ihre Ankunftszeit in Ortszeit mit.'],
    ]},
    { title: 'Formalitäten rechtzeitig erledigen', items: [
      ['t', 'Besorgen Sie für die Ankunft eine SIM oder eSIM und laden Sie Offline-Karten herunter.'],
      ['t', 'Konsularische Angelegenheiten (Pass, CNIE): Termine mehrere Monate vor der Abreise buchen.'],
      ['t', 'Operation Marhaba: Empfangsstellen (Häfen, Flughäfen, Straße) bieten im Sommer Information und Hilfe. Die Zeiträume veröffentlicht jedes Jahr die Stiftung Mohammed V für Solidarität.'],
    ]},
    { title: 'Bei der Ankunft: Kontrollen', items: [
      ['r', 'Auto: Anmeldung der vorübergehenden Einfuhr erledigt, Nachweis im Auto aufbewahrt.'],
      ['r', 'Versicherungsnachweis (Grüne Karte mit MA oder Grenzversicherung) im Auto aufbewahrt.'],
      ['t', 'Prüfen Sie Daten und Angaben der ausgehändigten Papiere, bevor Sie die Kontrollstelle verlassen.'],
      ['t', 'Heben Sie etwas Dirham ab und aktivieren Sie Ihre SIM / eSIM.'],
      ['t', 'Melden Sie der Familie Ihre Ankunft.'],
    ]},
    { title: 'Rückreise: Fahrzeug und 180 Tage', items: [
      ['r', 'Vorübergehende Einfuhr: **180 Tage pro Kalenderjahr**, an einem Stück oder in mehreren Aufenthalten. Keine Verlängerung, abgesehen von besonderen Jahresend-Regelungen, die beim Zoll zu prüfen sind. Überschreitung zieht Sanktionen nach sich.'],
      ['t', 'Notieren Sie Ein- und Ausreisedatum jeder Reise (siehe „Meine wichtigen Daten“) oder nutzen Sie den Zähler auf der Website.'],
      ['r', 'Bewahren Sie Einfuhrnachweis und gültige Versicherung bis zur Ausreise aus Marokko auf.'],
      ['r', 'Haustier: Gesundheitszeugnis für die Ausreise nach ONSSA-Muster mit kurzer Gültigkeit. Mit dem Tierarzt bestätigen.'],
      ['t', 'Die Rückreisen häufen sich Ende August: Verschieben Sie wenn möglich um einige Tage und seien Sie früh im Hafen.'],
      ['t', 'Prüfen Sie, dass Versicherung und Pässe auch die Heimreise abdecken.'],
    ]},
  ],
  guidesTitle: 'Zum Weiterlesen: Ratgeber auf der Website',
  guides: [
    ['summer-checklist', 'Checkliste Sommerrückkehr (interaktive Version)'],
    ['marhaba-guide', 'Operation Marhaba'],
    ['ferry-guide', 'Fähre nach Marokko'],
    ['car-180-days', 'Auto in Marokko: die 180-Tage-Regel'],
    ['car-insurance', 'Kfz-Versicherung: Grüne Karte oder Grenzversicherung'],
    ['customs', 'Zoll: Was Sie mitbringen dürfen'],
    ['passport-cnie', 'Pass und CNIE aus dem Ausland'],
    ['kids-pets', 'Kinder und Haustiere'],
    ['health-travellers', 'Gesundheit auf Reisen'],
  ],
  officialTitle: 'Offizielle Quellen',
  official: ['Marokkanischer Zoll (ADII): douane.gov.ma', 'Stiftung Mohammed V für Solidarität (Marhaba): fm5.ma', 'Konsulartermine: rdv.consulat.ma', 'Ausreiseerlaubnis für Minderjährige (Frankreich): service-public.fr', 'Grenzversicherung: Website des Anbieters (zum Beispiel CAT)'],
  disclaimerTitle: 'Allgemeine Information, keine Rechts- oder Steuerberatung',
  disclaimer: 'Diese Liste gibt Informationen aus unseren Ratgebern zum Ausgabedatum (Oktober 2026) wieder. Regeln, Beträge und Fristen ändern sich und hängen von Ihrer Situation ab. Prüfen Sie vor der Abreise beim Zoll (ADII), Ihrem Konsulat, Ihrer Versicherung und Ihrem Beförderer. Dieses Dokument ersetzt deren Auskünfte nicht. Es enthält keine Affiliate-Links. Maschinelle Übersetzung, menschliche Prüfung steht aus.',
  notes: 'Notizen',
  page: 'Seite',
};
