// English texts. 'r' = rule / requirement to confirm with the authority; 't' = practical tip.
export default {
  dir: 'ltr', locale: 'en-GB',
  docTitle: 'Summer Return to Morocco Checklist',
  subtitle: 'From departure to arrival and back: documents, transport, car, money, health, accommodation and paperwork.',
  edition: 'October 2026 edition',
  verify: 'Rules change: check before you travel.',
  legendTitle: 'How to read this list',
  legendRule: 'Rule',
  legendRuleText: 'a requirement or rule published in our guides. Confirm with the relevant administration, consulate, insurer or carrier.',
  legendTip: 'Tip',
  legendTipText: 'good practice, not mandatory.',
  legendBox: 'Tick a box when it is done.',
  keyDatesTitle: 'My key dates',
  keyDates: ['Departure date', 'Return date', 'Ferry / flight (booking number)', 'Car insurance valid until', 'Passports valid until', 'Vehicle entered Morocco on'],
  sections: [
    { title: 'Before you leave', items: [
      ['t', 'Book the ferry **in April-May** for a July-August departure: the best fares go early.'],
      ['t', 'Note the expiry dates of passports and ID cards for **the whole family**.'],
      ['t', 'Estimate your budget (crossing, fuel, tolls, stopovers, spending in Morocco) with the calculator on the site.'],
      ['t', 'If you are bringing the car, plan a mechanical check before departure (see "Vehicle").'],
      ['t', 'Tell your bank you are travelling abroad and test your bank card.'],
    ]},
    { title: 'Adult documents', items: [
      ['r', '**Valid passport** for the whole stay, for every family member. Moroccan nationals may also show a valid CNIE, but keep a passport in case of a check or a return flight.'],
      ['r', 'Foreign visitors: check the visa and entry conditions for your nationality with the authorities (see the visa guide on the site).'],
      ['t', 'Passport or CNIE to renew? **Allow 3 to 4 months**: consular appointments fill up fast in summer.'],
      ['r', 'Consular registration must be up to date before any renewal request at a consulate.'],
      ['t', 'Keep a digital and a paper copy of your documents, separate from the originals.'],
    ]},
    { title: 'Documents for children and pets', items: [
      ['r', '**Individual valid passport** for every child, whatever their age.'],
      ['t', 'Bring the family record book (or a birth certificate extract) to prove the link with the parents.'],
      ['r', 'Minor living in France travelling **without one parent**: exit authorisation (Cerfa form no. 15646, signed by a parent, with a copy of their ID).'],
      ['t', 'If a child is not travelling with both parents, also bring a signed parental authorisation, ideally legalised: Moroccan officers may ask for it.'],
      ['r', 'Dog or cat: microchip, rabies vaccination recorded in the EU pet passport, health certificate in the ONSSA format endorsed shortly before departure (confirm the exact window with your vet).'],
      ['t', 'Returning to the EU with a pet: the rabies antibody test takes several weeks. Start **at least 4 months** before the return.'],
    ]},
    { title: 'Transport: ferry, plane or road', items: [
      ['t', 'Ferry: in August, fixed-date tickets are generally required. Avoid weekends and the start or end of the month.'],
      ['t', 'Arrive at the port **about 3 hours before** boarding in peak season.'],
      ['t', 'Save tickets and bookings offline **and** print them.'],
      ['t', 'Check whether your ticket times are in local time: the time difference with Morocco can change with the season.'],
      ['t', 'Flying: check your airline\'s baggage allowance before buying bulky gifts.'],
      ['t', 'Road: break every 2 hours, especially at night in Spain. Keep water, snacks and documents within reach.'],
      ['t', 'No car in Morocco: book bus or train journeys (CTM, ONCF) in advance.'],
    ]},
    { title: 'Vehicle (if you drive)', items: [
      ['r', '**Original** registration document (or the owner\'s authorisation / power of attorney if it is not in your name) and a valid driving licence.'],
      ['r', '**Insurance valid in Morocco**: on the green card, the code **MA** must be present and not crossed out. Otherwise, buy border insurance on arrival (sold in fixed duration steps).'],
      ['t', 'Ask your insurer **before you leave** for a green card valid in Morocco. There is no single price for border insurance: ask the provider for a quote.'],
      ['r', 'Temporary admission: strictly personal and tourist use, declared to customs on arrival. Keep the proof until you leave Morocco.'],
      ['r', 'Do not let a Morocco resident drive your car without checking first: it is often prohibited.'],
      ['t', 'Mechanical check: tyres (spare included), brakes, fluids, air conditioning, battery. Load neatly, nothing on the rear shelf.'],
      ['t', 'Check tyre pressure cold and fill the tank the day before.'],
    ]},
    { title: 'Money and customs', items: [
      ['r', 'Currency: a declaration is required on arrival from the equivalent of **100,000 MAD**.'],
      ['t', 'Carry a little cash for the road and tolls; dirhams are obtained in Morocco (ATMs).'],
      ['t', 'Plan money transfers ahead and compare their real cost before sending.'],
      ['r', 'Gifts: personal belongings and reasonable gifts normally pass; large quantities or several identical new items (screens, phones, appliances) may be taxed. If in doubt, declare.'],
      ['r', 'Drone: importing one is prohibited without prior administrative authorisation. Leave it at home.'],
      ['t', 'Keep receipts for significant purchases.'],
    ]},
    { title: 'Health', items: [
      ['t', 'Check your routine vaccinations. For travellers from Europe, our guides list no mandatory vaccine; ask your doctor for advice.'],
      ['t', 'Take travel insurance with a high medical limit and repatriation: the European Health Insurance Card does not apply in Morocco.'],
      ['r', 'Personal medicines: original packaging, prescription or medical certificate in hand luggage. Controlled substances: doctor\'s letter and prior enquiries.'],
      ['t', 'Note the emergency numbers: SAMU 141, civil protection 15.'],
      ['t', 'Summer heat: stay hydrated, avoid midday sun, drink bottled water.'],
    ]},
    { title: 'Accommodation and stopovers', items: [
      ['t', 'Book your stopovers if the journey is long (a night in Spain, a night in Tangier) and check the cancellation terms.'],
      ['t', 'Write down the address of your first accommodation and a contact number in Morocco.'],
      ['t', 'With a pet: confirm that each stay and each cabin accepts animals.'],
      ['t', 'Tell family your arrival time, in local time.'],
    ]},
    { title: 'Paperwork to plan ahead', items: [
      ['t', 'Get a SIM or eSIM for your arrival and download offline maps.'],
      ['t', 'Consular procedures (passport, CNIE): book appointments several months before departure.'],
      ['t', 'Operation Marhaba: reception areas (ports, airports, roadside) provide information and assistance in summer. Dates are published each year by the Mohammed V Foundation for Solidarity.'],
    ]},
    { title: 'On arrival: checks', items: [
      ['r', 'Car: temporary admission declaration done, proof kept in the car.'],
      ['r', 'Insurance certificate (green card with MA, or border insurance) kept in the car.'],
      ['t', 'Check the dates and details on the documents you are given before leaving the post.'],
      ['t', 'Withdraw some dirhams and activate your SIM / eSIM.'],
      ['t', 'Let family know you have arrived.'],
    ]},
    { title: 'Coming back: vehicle and the 180 days', items: [
      ['r', 'Temporary admission: **180 days per calendar year**, in one or several stays. It cannot be extended, apart from special year-end provisions to check with customs. Overstaying brings penalties.'],
      ['t', 'Note your entry and exit dates on every trip (see "My key dates") or use the counter on the site.'],
      ['r', 'Keep the admission proof and valid insurance until you leave Morocco.'],
      ['r', 'Pet: export health certificate in the ONSSA format, with a short validity window. Confirm it with your vet.'],
      ['t', 'Returns bunch up in late August: if you can, shift by a few days and arrive early at the port.'],
      ['t', 'Check that your insurance and passports also cover the journey home.'],
    ]},
  ],
  guidesTitle: 'Go further: guides on the site',
  guides: [
    ['summer-checklist', 'Summer return checklist (interactive version)'],
    ['marhaba-guide', 'Operation Marhaba'],
    ['ferry-guide', 'Ferry to Morocco'],
    ['car-180-days', 'Taking your car: the 180-day rule'],
    ['car-insurance', 'Car insurance: green card or border insurance'],
    ['customs', 'Customs: what you can bring'],
    ['passport-cnie', 'Passport and CNIE from abroad'],
    ['kids-pets', 'Children and pets'],
    ['health-travellers', 'Health for travellers'],
  ],
  officialTitle: 'Official sources to consult',
  official: ['Moroccan Customs (ADII): douane.gov.ma', 'Mohammed V Foundation for Solidarity (Marhaba): fm5.ma', 'Consular appointments: rdv.consulat.ma', 'Exit authorisation for minors (France): service-public.fr', 'Border insurance: the website of the provider (for example CAT)'],
  disclaimerTitle: 'General information, not legal or tax advice',
  disclaimer: 'This checklist reflects information published in our guides at the edition date (October 2026). Rules, amounts and deadlines change and depend on your situation. Check before you travel with customs (ADII), your consulate, your insurer and your carrier. This document does not replace their guidance. It contains no affiliate links.',
  notes: 'Notes',
  page: 'Page',
};
